name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: thanhlp188/strapi-cms:v1

  deploy:
    needs: build
    environment:
      name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: |
          curl --request POST \
          --url ${{ vars.WEBHOOK_ENDPOINT }} \
          --header "Content-Type: application/json" \
          --header "x-webhook-signature: ${{ secrets.WEBHOOK_SECRET }}" \
          --data '{
              "inputs": {
                  "deployment": "strapi-cms",
                  "namespace": "strapi-cms"
              }
          }'